# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ae6b0b18413899016749e016dbdeae6c49d7751110cd1348a8aa9957e4e81fcccef65eab610b9c99f3c82bcae40490292cdc94fc487b3da0f144c5fd5f2af2c

test:
  secret_key_base: 9aa631eb794ac4bb230c40c904b487060dee54df566751c192a7d2494ed529df745e019431b6420bfde5371a339050bb38896db3e726fce80235df7a9522ffa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
